Check availability of NID images
Add a make target whose purpose is to run some prechecks to make sure we have
the required NID images before we proceed. We would run into problems later on
anyway but by running a few checks we can better probe our surroundings and give
hints to the user of what might be wrong.

Here are some example errors and hints that we could now receive based on
various input and the environment:

Image doesn't exist:

  kll@nuc:~/tailf/post-upgrade-actions$ make NSO_VERSION=5.3 build
  Checking NSO in Docker images are available...
  ERROR: The docker image cisco-nso-base:5.3 does not exist
  HINT: Set NSO_IMAGE_PATH to the registry path of the nso-docker repo, for example 'registry.gitlab.com/nso-developer/nso-docker/'
  make: *** [nidcommon.mk:106: check-nid-available] Error 1
  kll@nuc:~/tailf/post-upgrade-actions$

Image doesn't exist but one with the username postfixed does, like :5.3-kll
exist but not :5.3

  kll@nuc:~/tailf/post-upgrade-actions$ make NSO_VERSION=5.3 build
  Checking NSO in Docker images are available...
  ERROR: The docker image cisco-nso-base:5.3 does not exist
  HINT: You have a locally built image cisco-nso-base:5.3-kll, see the 'version-tag' make target to set the required tag on it
  HINT: Set NSO_IMAGE_PATH to the registry path of the nso-docker repo, for example 'registry.gitlab.com/nso-developer/nso-docker/'
  make: *** [nidcommon.mk:106: check-nid-available] Error 1
  kll@nuc:~/tailf/post-upgrade-actions$

Above messages are only for when NSO_IMAGE_PATH is empty, i.e. local builds. For
remotely hosted images we have missing trailing slash warning:

kll@nuc:~/tailf/post-upgrade-actions$ make NSO_VERSION=5.3 NSO_IMAGE_PATH=foo build
Checking NSO in Docker images are available...
ERROR: foocisco-nso-base:5.3 not found
HINT: did you forget a trailing '/' in NSO_IMAGE_PATH?
make: *** [nidcommon.mk:106: check-nid-available] Error 1
kll@nuc:~/tailf/post-upgrade-actions$

and complete failure to find the image:

kll@nuc:~/tailf/post-upgrade-actions$ make NSO_VERSION=5.3 NSO_IMAGE_PATH=foo/ build
Checking NSO in Docker images are available...
ERROR: foo/cisco-nso-base:5.3 not found
HINT: Is NSO_IMAGE_PATH correctly set? Set NSO_IMAGE_PATH to the registry URL of the nso-docker repo, for example 'registry.gitlab.com/nso-developer/nso-docker/'
make: *** [nidcommon.mk:106: check-nid-available] Error 1
kll@nuc:~/tailf/post-upgrade-actions$